### ISSUE TITLE
repo-include failing on rhel8 and rhel9: *** wrong version of package-1 was installed

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#670]
repo-include test is failing on rhel8 and rhel9 scenarios:
```
stdout:
*** wrong version of package-1 was installed
*** unable to find marker for package-1

2022-02-17 01:22:42,172 INFO: RESULT:repo-include:7f8a0daed3b6:FAILED:Validation failed with return code 1
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/8086557/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/8086559/virt-install.log)

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/671

**Comment by poncovka** [comment]
The `repo --includepkgs` command doesn't work in RHEL 8 and RHEL 9, because we don't set the right DNF configuration options. The `repo --excludepkgs` shouldn't work as well, but there is probably a bug in DNF. See [0], [1] and [2].

From `pyanaconda/payload/dnf/payload.py`:

```
        if ksrepo.includepkgs:
            repo.include = ksrepo.includepkgs

        if ksrepo.excludepkgs:
            repo.exclude = ksrepo.excludepkgs
```
It should be changed to:

```
        if ksrepo.includepkgs:
            repo.includepkgs = ksrepo.includepkgs

        if ksrepo.excludepkgs:
            repo.excludepkgs = ksrepo.excludepkgs
```

[0] [Reintroduction of YUM’s configuration options includepkgs and excludepkgs](https://dnf.readthedocs.io/en/latest/dnf-1_vs_dnf-2.html?highlight=includepkgs#reintroduction-of-yum-s-configuration-options-includepkgs-and-excludepkgs)
[1] https://dnf.readthedocs.io/en/latest/conf_ref.html#include-label
[2] https://dnf.readthedocs.io/en/latest/conf_ref.html#exclude-label

**Comment by jkonecny12** [comment]
RHEL-8 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2014103

**Comment by rvykydal** [comment]
> RHEL-8 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2014103

RHEL-9 clone: https://bugzilla.redhat.com/show_bug.cgi?id=2158210

**Comment by rvykydal** [comment]
Closed by https://github.com/rhinstaller/kickstart-tests/pull/864
